// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart';
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4PMbIpfodZVyDLyTtuE5ctfS_EZ9TRmg',
    appId: '1:571140693827:web:a9621c82137027a19719f6',
    messagingSenderId: '571140693827',
    projectId: 'livestreamapplication-17409',
    authDomain: 'livestreamapplication-17409.firebaseapp.com',
    storageBucket: 'livestreamapplication-17409.appspot.com',
    measurementId: 'G-HE9HCCGQTW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHmt7RTFzMA2AYiGWJPkG0S5j6gUPCADM',
    appId: '1:571140693827:android:807d37dbd5b759a69719f6',
    messagingSenderId: '571140693827',
    projectId: 'livestreamapplication-17409',
    storageBucket: 'livestreamapplication-17409.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGfa3gLjPuwdOl1foIzkglq6mdHECyQJ0',
    appId: '1:571140693827:ios:2b2825cf605f77469719f6',
    messagingSenderId: '571140693827',
    projectId: 'livestreamapplication-17409',
    storageBucket: 'livestreamapplication-17409.appspot.com',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGfa3gLjPuwdOl1foIzkglq6mdHECyQJ0',
    appId: '1:571140693827:ios:2b2825cf605f77469719f6',
    messagingSenderId: '571140693827',
    projectId: 'livestreamapplication-17409',
    storageBucket: 'livestreamapplication-17409.appspot.com',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4PMbIpfodZVyDLyTtuE5ctfS_EZ9TRmg',
    appId: '1:571140693827:web:6d0d096fe5c7615b9719f6',
    messagingSenderId: '571140693827',
    projectId: 'livestreamapplication-17409',
    authDomain: 'livestreamapplication-17409.firebaseapp.com',
    storageBucket: 'livestreamapplication-17409.appspot.com',
    measurementId: 'G-843V029X4B',
  );
}


